### ISSUE TITLE
`Error: getaddrinfo EAI_AGAIN` when connecting to Infura with `--infura` flag set

### ISSUE THREAD

**Issue by chrishobcroft** [FuelLabs/fuel-js#10] opened 2021-01-05 15:00 UTC
### Summary

I'm experiencing a UX issue when running `fuel` against a remote RPC endpoint provided by [Infura](https://infura.io/).

Running the pre-compiled binary results in the code reporting a stack trace and then exiting.

### Observed behaviour

I run `./fuel --network="mainnet" --infura="********c40b4d538f126b1e5520eca2"` and then I see this:
```
✔ Please enter your Fuel wallet decryption passphrase … ************
fuel-2021-01-05 8:09:56 PM : Using API key: ********c40b4d538f12...
fuel-2021-01-05 8:09:56 PM : Using Infura provider
fuel-2021-01-05 8:09:56 PM : Wallet/operator address used: 0x****************eB6144fACaD91956********
fuel-2021-01-05 8:09:56 PM : DB: default local db selected.
{ Error: invalid response - 0
    at exports.XMLHttpRequest.request.onreadystatechange (/snapshot/client/node_modules/ethers/utils/web.js:84:29)
    at exports.XMLHttpRequest.dispatchEvent (/snapshot/client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/snapshot/client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at exports.XMLHttpRequest.handleError (/snapshot/client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (/snapshot/client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
  statusCode: 0,
  responseText:
   'Error: getaddrinfo EAI_AGAIN mainnet.infura.io mainnet.infura.io:443\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)' }
attempting exit
``````
This also happens when running `./fuel --network="mainnet" --rpc="https://mainnet.infura.io/v3/********c40b4d538f126b1e5520eca2"`

This is running against an Infura "Core" Account (free up to 100,000 requests per day).

### Expected behaviour

Well, I don't really know for sure what I would expect at this point. I mean, I'm running a piece of pre-compiled binary software against an opaque third-party infrastructure provider - I guess I'm expecting it should do more than it does, perhaps allow me to do things like deposit funds from mainnet, then transfer funds to other ETH addresses, and to withdraw somehow back onto mainnet - perhaps via some calls from [fuel-js](https://github.com/FuelLabs/fuel-js).

But I've got little to no clue about what I expect to see in the logs, about what the node is doing, perhaps something about monitoring the L1 chain for deposits into some kind of contract, like in eth2, or creating / destroying private records of transactions which allow recipients of transfers to prove that they are entitled to some kind of funds.

So, I'll just say this: I expect it to do more than it currently does, and I expect that whatever the error is, that the code should be aware that something like this might happen, and that it could report some message to help me, as the user, to better understand what I should do next (if indeed there's anything I can do).

### Environment

![image](https://user-images.githubusercontent.com/2212651/103455514-c46b0f00-4d13-11eb-81d1-84f53f1767a1.png)

**Comment by SilentCicero** [comment] 2021-01-05 16:01
Thanks @chrishobcroft, debugging this now.

**Comment by SilentCicero** [comment] 2021-01-07 03:36
@chrishobcroft this could be caused by numerous networking things.

Upon further investigation, the binaries and code work on compatible `linux` environments with an Infura `Core` account without issue.

We can try the next patch and see if that resolves it for you, although I haven't made any significant changes directly. I've added some better network checking steps before hand to try and alleviate this issue where possible (but namely with the RPC at this stage).

**Comment by SilentCicero** [comment] 2021-02-11 15:38
I don't see a resolution path for this at the moment. Closing for now. If this does keep happening, please feel free to reopen.

**Closed by SilentCicero** 2021-02-11 15:38 UTC
Labels: bug
